### ISSUE TITLE
Crashes if I take too long/maybe autosave?

### ISSUE THREAD

**Issue by 5731la** [RyuzakiKK/NoteCrypt#52] opened 2019-03-07 14:49 UTC
I have to type in a different editor and then copy it over because of this

**Comment by RyuzakiKK** [comment] 2019-03-18 09:38
I tried to keep the note edit page open for about 40 minutes and I was unable to reproduce the crash.
Are you able to reliably reproduce this bug? If so, what are the exact steps?

**Comment by RyuzakiKK** [comment] 2020-02-28 15:36
I'm closing this but feel free to report back if it is still happening

**Closed as completed by RyuzakiKK** 2020-02-28 15:36 UTC
